### ISSUE TITLE
missing dash parameters

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#126]
dashes must be in integers, and therefore can't be shorter than the width of the line

**Comment by nvkelso** [comment]
What do you mean by `can't be shorter than the width of the line`?

**Comment by meetar** [comment]
The code defining the dash behavior pegs the value of "1" to the width of the line drawn in the associated style, and also requires that the dash pattern be denoted in integers only, thus there is no way to draw a dash which is shorter than the width of the line it is on using this parameter … I might make a diagram.

**Comment by nvkelso** [comment]
Got it, thanks :) I think your other issue is good enough (without the illustration).

**Comment by meetar** [comment]
fixed with https://github.com/tangrams/tangram-docs/pull/127
