### ISSUE TITLE
Is shader configuration in its own block?

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#13]
According to 

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#shaders 

the "defines", "uniforms", and "blocks" elements are direct children of the "style" block; but here

https://github.com/tangrams/tangram/blob/master/demos/scene.yaml#L53

the shader elements are children of a block called "shaders".

**Comment by bcamper** [comment]
`uniforms` etc. are nested under `shaders` -- but I'm not seeing that in the first link? Maybe I'm just missing where and there are mixed examples?

**Comment by matteblair** [comment]
Looks like the nesting is off in the docs page, I'll fix it right after lunch!

**Comment by matteblair** [comment]
Fixed https://github.com/tangrams/tangram-docs/commit/9d52adc9649e459ca3bb1fe2230d2f3ea0917bc7
