### ISSUE TITLE
raster source

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-docs#134]
I try to create maps from raster source in my android app. I took exampe of scene.yaml from mapzen documentation.
'sources:
terrain-normals:
type: Raster
url: https://terrain-preview.mapzen.com/normal/{z}/{x}/{y}.png
mapzen-osm:
type: TopoJSON
url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson
rasters: [terrain-normals]

styles:
normals:
base: polygons
raster: normal

lights:
point1:
type: point

layers:
earth:
data: { source: mapzen-osm }
draw:
normals:
color: white
order: 0'

**Comment by meetar** [comment]
Hello @ivangorelow, your example works for me here: https://mapzen.com/tangram/play/#3.3170/15.56/-68.67

If you have a bug or question about the Tangram-ES library, please file an issue here: https://github.com/tangrams/tangram-es/issues
