### ISSUE TITLE
per-draw-style shader parameters

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#137]
In Styles-Overview.md, this kind of phrase is included a few times, without further elaboration:

> #### `polygons` shader specs
> 
> The `polygons` style allows [shaders](shaders.md) to be written which take advantage of certain unique attributes and uniforms.

I believe I wrote that intending to fill in details later, but I don't remember what this is talking about. Any ideas?

**Comment by bcamper** [comment]
Hm, doesn't really make sense strictly since _any_ style allows "custom shaders". Maybe very old (before some other styles). I would cut it and we can separately ensure the shader pieces are documented.

**Comment by meetar** [comment]
:+1:

removed with https://github.com/tangrams/tangram-docs/commit/aac88f42cb3e39752bdbec616de2b43a13a7dfec
