### ISSUE TITLE
Lighting type configuration

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#14]
In a demo stylesheet, lighting type for a style is explicitly set: 

https://github.com/tangrams/tangram/blob/master/demos/scene.yaml#L69

This parameter isn't documented. Is this the only way that lighting type is set?

**Comment by meetar** [comment]
You're right, this fell through the cracks – I believe this is a simple Boolean – @bcamper ?

**Comment by meetar** [comment]
It can be 'vertex', 'fragment', or 'false' - docs udpated with https://github.com/tangrams/tangram-docs/commit/f8a8a9d6eb5a15d1199fd05ac7c50318bd133a58
