### ISSUE TITLE
Unclear how to specify units

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram-docs#140]
The width documentation states

> Units are meters `m` or pixels `px`. Default units are `m`.

Searching through the documentation does not reveal
- How to change the units
- If meters or mercator meters are used

In my case I had width as the function A_exp(b_z) so I could transform it to pixels 156250_A_exp((b-ln(2))*z), but I think more naturally in px.

**Comment by meetar** [comment]
Resolved with https://github.com/tangrams/tangram-docs/commit/971ee331e47f454e9451232a285f3c76a1dee4f0

**Comment by pnorman** [comment]
How does this apply to the use of functions, e.g. if I have `width: function () { return 0.15*Math.exp(0.25 * $zoom) }`

**Comment by meetar** [comment]
You should be able to simply append the string "px" to your value to change the units, like so:

`width: function () { return 0.15*Math.exp(0.25 * $zoom) + "px"; }`

…However, I'm having trouble with that myself at the moment, issue filed here: https://github.com/tangrams/tangram/issues/392

**Comment by pnorman** [comment]
Oh, are the units meters or mercator meters? If the former, it allows for rendering based on the true scale of the map. The latter is what is normal for web maps.

**Comment by bcamper** [comment]
The units are **mercator meters**. We should update the docs to clarify that, thank you for flagging.
