### ISSUE TITLE
how smart is loadTextures()?

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#145]
I see loadTextures() only returns the name and size of the textures – so does it really force-reload all textures, or is it able to check for size differences and just reload ones which have changed?

**Comment by bcamper** [comment]
The logic is here: https://github.com/tangrams/tangram/blob/master/src/gl/texture.js#L407-L422

If any of the texture definition's parameters changed, OR if the texture is tied to an `element`, the texture is reloaded.

**Comment by meetar** [comment]
Added detail in https://github.com/tangrams/tangram-docs/commit/6a5ae65d28e1f7daaf009818f5f11ac22e184fdb
