### ISSUE TITLE
Shader blocks: "filter" vs "color"

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#15]
It seems like this example should read 

``` yaml
blocks:
    filter: color.rgb = vec3(1.0, .5, .5);
```

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#filter

**Comment by meetar** [comment]
Fixed with https://github.com/tangrams/tangram-docs/commit/cb110c9c77637569724cf672d21bba8233e272c3, thanks!
