### ISSUE TITLE
Update references to vector.mapzen.com URLs in Tangram docs

### ISSUE THREAD

**Issue by rmglennon** [tangrams/tangram-docs#152]
I found a few lingering references to the vector.mapzen.com URL. 

From a quick search in the published help, looks like maybe seven topics, but I did not pull the source files to look thoroughly. Anything in the form of https://vector.mapzen.com should go to the 1.0 scheme, like http://tile.mapzen.com/mapzen/vector/v1. Also may want to consider whether all of these should remain, or if we can put in one place and link. 

cc @nvkelso @migurski @kkowalsky 

![image](https://cloud.githubusercontent.com/assets/4380498/19912861/00880278-a05b-11e6-9eca-9ecf52e69862.png)

**Comment by kkowalsky** [comment]
@meetar weren't you in the process in updating the tangram demos to use v1 tiles? If not, we should be sure to do that as well

**Comment by meetar** [comment]
Yep! All the appropriate demos have been updated, the docs are last on my list.

**Comment by meetar** [comment]
fixed with https://github.com/tangrams/tangram-docs/commit/9d4e715dd6d94df6e1e4b2349ffeffbe6d43e89f
