### ISSUE TITLE
Is linear texture filtering available?

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#17]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/textures.md#filtering

I'm guessing that texture filtering is linear if nothing is set. If that's the case we should document it so that the effect of leaving it unset is clear.

**Comment by matteblair** [comment]
And the page says that this parameter "Sets the filtering mode for sprites" but I suspect it affects all texture usages, not just sprites.

**Comment by bcamper** [comment]
Yes, `filtering` defaults to (and can be explicitly set to) `linear`, and yes, it would affect any usage of that texture!

**Comment by meetar** [comment]
Fixed with https://github.com/tangrams/tangram-docs/commit/030cc783be96e78f84433b30d6f0d37a1a0515e0, thanks!
