### ISSUE TITLE
Deprecate `centroid` (replaced by `placement: centroid`)

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-docs#178]
The `centroid: true` parameter (https://mapzen.com/documentation/tangram/draw/#centroid) has been deprecated, and replaced by the `placement: centroid` parameter (https://mapzen.com/documentation/tangram/draw/#placement)

**Comment by meetar** [comment]
fixed with https://github.com/tangrams/tangram-docs/commit/787c8b1813d906b333f94f6466659977d2f75893
