### ISSUE TITLE
Add note about priority only applying within a source

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-docs#182]
I helped @burritojustice with some thematic layering in Tangram today and was reminded that labels only collide for a single source

If I have sources A, B, and C I can't set priorities to allow features in each of the sources to collide across layers across sources. Instead the priority seems to only apply in the same source, and the labels effectively overlap each other.

We should document this behavior, and look into changing Tangram to allow collisions across sources in the future (separate issue).

**Comment by bcamper** [comment]
Yes, collisions across sources is a pretty annoying issue for dataviz. It's documented as a need: https://github.com/tangrams/tangram/issues/365. Unfortunately there are a couple aspects of the problem that make it pretty knotty (with our current collision architecture), so we need to evaluate solutions (either find something that works now, or consider moving collision to the main thread, which we have long considered).

**Comment by matteblair** [comment]
The documentation should also note that in tangram-es, labels from different sources **do** collide with one another.

**Comment by meetar** [comment]
Resolved with https://github.com/tangrams/tangram-docs/commit/121cfe11bcd043882471fcfa70a3f01a14915c78, https://github.com/tangrams/tangram-docs/commit/e0bf71b723bcc6656cfd8329f31b7ad87a4ce8d1, and https://github.com/tangrams/tangram-docs/commit/2badf60c972cec17bddd4613945225328c14acf5.
