### ISSUE TITLE
Fix doc to mention RGBA color values

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-docs#19]
Documentation states that color be specified as: [R, G, B] or #rrggbb or css style color. 
But it should be legal to have a color with RGBA value.

For example refer: 
https://github.com/tangrams/tangram-docs/blob/f93ae00113e4db842e014e9de0ede1b201039ea9/pages/materials.md#diffuse

**Comment by meetar** [comment]
I believe that the styles currently only accept vec3s, as the library does not currently support any alpha values apart from 1.0 – @bcamper, is this accurate?

**Comment by meetar** [comment]
the word is "yes and no" – RGBA is legal, but alpha is currently ignored. I'll update the docs.
