### ISSUE TITLE
reserved keywords clarification

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#20]
When describing restrictions on the custom names of objects, the "reserved keywords" are mentioned, in numerous places:

cameras.md#camera-names
lights.md#light-names
sources.md#source-names
styles.md#style-names
textures.md#texture-names
layers.md#layer-name
layers.md#sublayer-name
layers.md#properties

This was originally written with the understanding that there were globally-reserved keywords, and that none of them could be used as custom names in any of these circumstances. Is this true?

Or – is it that a custom name can be anything except one of the reserved keywords _at that layer in the document_ – and if there aren't any at that layer, the name can be anything at all?

Eg a `layer` object can take `data` and `filter` parameters (in addition to any sublayers), so the sublayers can be named anything except "data" and "filter" – whereas the `cameras` object has _only_ custom names as parameters, so those names can be anything?

cc @bcamper

**Comment by bcamper** [comment]
Reserved words are context-sensitive. For example, a layer can have any name except for `data`, `filter`, or `properties`. But a camera or light can be named `data`, for example.

**Comment by meetar** [comment]
Fixed by https://github.com/tangrams/tangram-docs/commit/9853801cfb5ca5e706de637c14f694b3a0e4b574
