### ISSUE TITLE
Fix top-level links in documentation sidebar

### ISSUE THREAD

**Issue by Scarysize** [tangrams/tangram-docs#206]
<img width="285" alt="screen shot 2017-04-05 at 12 03 19" src="https://cloud.githubusercontent.com/assets/10571630/24700611/effb3b8e-19f7-11e7-9934-20f93d44b2d4.png">

The top-level links like "Getting started", "Syntax reference" etc. should link to their first sub item. Currently the link to '#', which scrolls the page to the top, but you are still at your last location.

A small nit pick, but super confusing.

**Comment by meetar** [comment]
Thanks for the feedback @Scarysize! We're in the process of revamping our docs-building process, which should resolve this issue. I'll keep this open until then.

**Comment by meetar** [comment]
Resolved with migration to readthedocs
