### ISSUE TITLE
Point light position coordinate order

### ISSUE THREAD

**Issue by Scarysize** [tangrams/tangram-docs#207]
The docs state that for a `point` light with `origin: world` the `position` can be set via `[lat, long]`. After some confusing minutes I found out, that it's actually `[long, lat]`; the other way around.

I don't know what your "default" order for geo coordinates is, so I don't know if the documentation or the implementation is faulty here. That's why I didn't open a PR to correct this.

**Comment by meetar** [comment]
You're absolutely right, the docs are wrong. Fixed with https://github.com/tangrams/tangram-docs/commit/dbd5cfc3e78a4b7622b4965d6cc26405ead11e21
