### ISSUE TITLE
`base` vs `mix`

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#22]
According to https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/styles.md a style can "inherit" or "descend" from one of the built-in styles, in which case you use `base`, or from another named style, in which case you use `mix`.

Is there any other difference between `base` and `mix`? Do I recall that `mix` can take a list of styles?

cc @bcamper

**Comment by bcamper** [comment]
They are very distinct functions. (In a previous, pre-`mix` incarnation, these two functions were more closely bound into one feature, but that was not flexible enough.)

`base` defines the expected input geometry type, and the vertex and fragment shader used for rendering (which custom blocks are then injected into). `base` can only be one of `polygons`, `lines`, `points`, or `text`.

`mix` copies properties from one or more custom styles. You can't `mix` the base types like `polygons`, instead `mix` acts more like inheritance. But the best way to think about it is as something that copies properties from another style. For example, to create a new style called `styleB` that "inherits from" an existing style called `styleA`, and then adds custom shader blocks to `styleB`, you would do:

```
styleB:
   mix: styleA
   shaders:
      blocks:
         color: ...
```

You can change any property of a `mix`'ed style, including its `base`. For example, if you have a polygon-based style that has custom shader blocks that you want to apply to lines instead, you can create a line-based version like this:

```
fancy-lines:
   mix: fancy-polygons
   base: lines # change the base to lines
```

Or you could `mix` in an existing style, but disable lighting:

```
fancy-but-no-lighting:
   base: fancy
   lighting: false
```

If multiple styles are `mix`'ed, the properties are copied from them in order, with the later styles taking precedence over earlier ones, e.g. `styleC` properties will overwrite those in `styleB` (which will overwrite them in `styleA`):

```
styleD:
   mix: [styleA, styleB, styleC]
```

The `mix` parameter is also useful for mixing multiple effects together, e.g. to apply both the windows and halftone effects simultaneously:

```
weird:
   mix: windows, halftone
```

**Comment by meetar** [comment]
Excellent, thanks for the details – I'll update the docs.

**Comment by meetar** [comment]
fixed in https://github.com/tangrams/tangram-docs/commit/633a85212f9a0cf62677a091ebd8e572e6dfa257
