### ISSUE TITLE
Draw order and blending

### ISSUE THREAD

**Issue by davidmanzanares** [tangrams/tangram-docs#224]
Hi,
I think this needs  some clarification:

> Note that by default, points and text layers are drawn with the overlay draw style, which relies on collision tests to determine draw order, as determined by a feature’s priority

(in https://mapzen.com/documentation/tangram/draw/#order )

My questions are: what are those collision tests? why are they needed? why the `order` must be defined with other blending modes but it can be undefined if `blend` is `overlay`?

And a small suggestion, could you add in https://mapzen.com/documentation/tangram/styles/#blend a mention of the side effect (the fact that if blend is set to not `overlay`, then `order` must be defined).

Thanks!

**Comment by meetar** [comment]
@dv343 Yep, you're right! The collision tests are just the ones determined by the `collide` setting, which with `priority` determine which points/labels are drawn and in what order. The mention of "collision tests" was muddying the water there, so I moved it and clarified the cases when `order` is required.

Thanks very much for the feedback!

**Comment by meetar** [comment]
Oh, and to answer your question – with "overlay", everything is drawn using traditional alpha compositing _on top_ of every other feature in the scene, using the painter's algorithm. So it's outside of the whole concept of "layer order" that the rest of the scene uses. Instead, which things are drawn and in what order is determined by the features' `priority` and the draw group's `collide` settings.

Hope this clarifies things!

**Comment by meetar** [comment]
Resolved with https://github.com/tangrams/tangram-docs/pull/225
