### ISSUE TITLE
Non-Mapzen hosted documentation

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram-docs#239]
With the shutdown of Mapzen, are there plans to switch where the documentation is hosted?

**Comment by matteblair** [comment]
https://readthedocs.org? Looks like there is already a project started for it: https://readthedocs.org/projects/tangram-js/

**Comment by pnorman** [comment]
cc @meetar who's started the project.

There's three different items, all related, all which need documentation

- Tangram JS
- Tangram ES
- The Tangram Scene File language

As a cartographer, it's the third I'm interested in. readthedocs is typically used with projects like the first two where there's an API, but I don't know of any reason why it wouldn't work for the third.

**Comment by meetar** [comment]
https://tangrams.readthedocs.io/en/latest/
✅ ✅ ✅
