### ISSUE TITLE
File structure for compatibility with mkdocs pipeline

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-docs#24]
Summary of conversation from today.

First, for reference:
- Repository for mkdocs pipeline: ~~https://github.com/louh/tangram-mkdocs~~ Moved to https://github.com/mapzen/mapzen-docs-generator
- Build files published to gh-pages: http://louh.github.io/tangram-mkdocs/

And some additional background:
The contents of https://github.com/tangrams/tangram-docs is pulled in as a git submodule (for now, submodules are super janky) and [MkDocs](http://mkdocs.org/) is [told](https://github.com/louh/tangram-mkdocs/blob/master/mkdocs.yml) to read contents from the [pages directory](https://github.com/tangrams/tangram-docs/tree/gh-pages/pages) (as opposed to the root of the repository, most of which contains demo files, instead of documentation).

Some of the issues which have arisen:
- MkDocs does not understand contents outside of the documentation directory you give it, so relative links that go up to the root and into another folder just result in broken links. This results in things like image files ([which GitHub links to correctly](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Materials-Overview.md)) to [break when rendered by MkDocs](http://louhuang.com/tangram-mkdocs/Materials-Overview/). A potential solution is to move image assets into the `pages` folder if it's not needed anywhere else, or we process documentation from the root directory of the repository instead.
- Similarly, the [front page of the documentation](http://louhuang.com/tangram-mkdocs/) is processed by making a copy of [README.md](https://github.com/tangrams/tangram-docs/blob/gh-pages/README.md) and placing it in the `pages` folder as `index.md` (with paths corrected). (I originally said it was based off of `pages/Home.md` but I think I was wrong about that.) For some reason we had some linking issues arising from case sensitive filenames but as I'm digging into the root cause, I think it might actually be a workflow problem on my end, so I will try to address it on my side and see if it's still a problem. On a similar vein, though, would it make sense to just have lower-case file names so that URLs are cleaner?
- Organization of things into certain top level categories makes it easier to do things like concatenate smaller pieces of documentation into single pages (this makes sense in technical documentation, like API or language documentation, where developers are more likely to prefer to Ctrl-F to a term). (Examples: [LESS](http://lesscss.org/features/), [Leaflet](http://leafletjs.com/reference.html)) Some ways we discussed (each with their own tradeoffs):
  - Explicitly declare which file is categorized where in mkdocs configuration.
  - Sort files into subfolders that are intended to indicate how files are categorized.
  - Include a block of YAML metadata (like with Jekyll posts) that tell the pipeline what to do with it.

**Comment by meetar** [comment]
Things I am totally cool with:
- lower-case doc names
- new docs structure
- folders for top-level categories
- yaml matter

**Comment by meetar** [comment]
Just made a new branch called 'reorg' with the image files moved around and all the img links changed to match:

https://github.com/tangrams/tangram-docs/tree/reorg

Let's use this as a test run for the mkdocs scheme, and once it's working we can discuss the rest of the structure.

**Comment by meetar** [comment]
@rmglennon The 'reorg' branch is now cleaned up, with all the modified content moved to the 'gh-pages' branch -- it is now ready for your changes.

**Comment by rmglennon** [comment]
Thanks, @meetar!

**Comment by meetar** [comment]
Merged reorg into gh-pages: https://github.com/tangrams/tangram-docs/commit/a1ab5a9c84dcb13892ac1f65909411af2d662110

Now considering https://github.com/tangrams/tangram-docs/tree/lou/folder-structure

**Comment by meetar** [comment]
Considering this closed now that the github > docs flow is stable.
