### ISSUE TITLE
Filter inheritance

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram-docs#242]
[The filter inheritance section](https://mapzen.com/documentation/tangram/Filters-Overview/#inheritance) states 

> Higher-level filters continue to apply at lower levels, which means that higher-level `draw` parameters will be inherited by lower levels, unless the lower level explicitly overrides it.

I originally thought this was wrong about the use of overrides for where additional filters apply additional criteria. Now I see it's talking about the `draw` parameters, which is confusing in this context.

**Comment by matteblair** [comment]
Can you explain your first interpretation of this section? Familiarity makes these things harder to see from fresh perspectives.

**Comment by pnorman** [comment]
I guess the question is if the "unless the lower level explicitly overrides it" clause applies to the "Higher-level filters continue to apply at lower levels" or "which means that higher-level draw parameters will be inherited by lower levels" clause.

My experience tells me that it applies to the second clause, which is what Tangram actually does. I think this is backed up by a strict parsing of the sentence, but I'm not 100% sure. It should be clearer.

**Comment by tallytalwar** [comment]
>  "which means that higher-level draw parameters will be inherited by lower levels"

Yup thats how its implemented on JS and ES and your explicit wording in the PR makes sense.

Thanks @pnorman
