### ISSUE TITLE
Keyword Property: $zoom needs clarity

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-docs#25]
[Keyword-properties](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Filters-Overview.md#keyword-properties), mention "$zoom" to be the value of "current zoom". Will it make sense to mention "tile zoom" instead of "current zoom".

I got confused and thought it to be the value of the view's zoom initially.

**Comment by meetar** [comment]
It is in fact the current zoom level of the map – fixed with https://github.com/tangrams/tangram-docs/commit/00c8e6eb21e8fa33263ea9d45c5b72fb474a4557 – thanks!
