### ISSUE TITLE
Are layer "properties" entries inherited?

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#28]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/layers.md#sublayer-name

The **sublayer name** section says that the `draw` and `filter` definitions are inherited. Is the `properties` entry inherited as well? We may want to specify that in the docs, either way.

**Comment by meetar** [comment]
Yep, they sure are – clarified with https://github.com/tangrams/tangram-docs/commit/1f9b75543287452d4f7ed9f941136a702f908401, thanks!
