### ISSUE TITLE
Filter matching example syntax

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#29]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Filters-Overview.md#matching-collisions

These examples have sublayers with a field called 'style', is this legal or does there need to be a 'draw' wrapping it?

**Comment by tallytalwar** [comment]
According to [this](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/layers.md#draw). draw is a mandatory field for layer/sublayers. And style should be a field under draw.

**Comment by matteblair** [comment]
Yup, looks like a boo boo. I'll fix this one.

**Comment by matteblair** [comment]
Fixed: 4d7e0a2b96fbaa5430b42c3ab4e8167624b9fe77

**Comment by meetar** [comment]
yep – that example was wicked old, and somehow escaped the Great Purge. thanks!
