### ISSUE TITLE
'list' vs 'sequence', 'object' vs 'mapping'

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#30]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Filters-Overview.md#lists-imply-any-objects-imply-all

We should probably refer to them as 'sequence' and 'mapping', as the spec does: http://yaml.org/spec/current.html#id2506659

**Comment by meetar** [comment]
I'm cool with "mapping", it's a more specific clue to its behavior than "object" – but I'm not sure about "sequence"… is there anything implied by "sequence" that "list" doesn't cover? I'd prefer to use the simplest accurate language as much as possible, and I doubt anybody will be confused that we're not hewing to the spec's terms…

**Comment by meetar** [comment]
"Objects" - > "Mappings" with https://github.com/tangrams/tangram-docs/commit/90d1bd0b5e396f7907ae5c862d6f77b0dd750f14

**Comment by matteblair** [comment]
Yeah you're right, 'list' is perfectly intuitive here. Thanks :)
