### ISSUE TITLE
Filters-Overview.md refers to a data.md file that does not exist

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-docs#35]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Filters-Overview.md (line 18). Please advise. Is this link supposed to point to something that has been renamed, to a file that doesn't exist yet, or ...?

**Comment by meetar** [comment]
Yep, there were a few broken links in that section, fixed with https://github.com/tangrams/tangram-docs/commit/d04cbbf26b0c8c54c66ea10ecd0ef885f5227323 - thanks!
