### ISSUE TITLE
Scene-file.md refers to styling-rules.md that does not exist

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-docs#36]
See here: https://github.com/tangrams/tangram-docs/blame/reorg/pages/Scene-file.md#L25

**Comment by louh** [comment]
I just realized that reorg branch is tons of commits behind gh-pages, sorry if this is fixed already

**Comment by meetar** [comment]
Fixed in gh-pages with https://github.com/tangrams/tangram-docs/commit/fb11c413bb69d655d58899ef51903f2119b81877, I'll merge it into reorg when we do the switchover – thanks!
