### ISSUE TITLE
Size param for sprites

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-docs#41]
It seems like the [size](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#size) parameter isn't fully documented since it's possible to provide a `[widhSize, heightSize]` if the sprite isn't squared.

**Comment by meetar** [comment]
Fixed with https://github.com/tangrams/tangram-docs/commit/e6b9a023b01242cb09dee5b541ddea6479d232f4 – thanks!
