### ISSUE TITLE
u_map_zoom?

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#42]
Is it a thing? Can't seem to find/use it.

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#built-in-uniforms

**Comment by hjanetzek** [comment]
We have it as 'u_zoom' set in style.cpp. It's used in line scaling

**Comment by bcamper** [comment]
It's `u_map_position.z` (.xy are the map center in meters).

**Comment by bcamper** [comment]
https://github.com/tangrams/tangram-docs/commit/537db4f4e12f2546a20107f54f5ca9efff8bce47
