### ISSUE TITLE
Update shader blocks to include "width" block

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-docs#43]
At present shader blocks documentation mentions 5 shader blocks namely `global`,`position`,`color`,`normal`,`filter`. (refer: [here](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#blocks))

It seems `width` is also used as a shader block in the style sheets (including [eraser map style sheet](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L615)).

**Comment by meetar** [comment]
Thanks – fixed with https://github.com/tangrams/tangram-docs/commit/83349b504979ea6495aa32e8da626443b46f1c71 – can I get a check for accuracy @bcamper?

**Comment by meetar** [comment]
Adjusted block order: https://github.com/tangrams/tangram-docs/commit/5a9fe69131f5054e7f8bcf60ca8095fa3deb957a
