### ISSUE TITLE
Behavior of "required" values when invalid value is returned from function

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#49]
Some draw rules are described as "required" and have "no default", but can also have functions assigned to them. 

One such rule is `color`: 
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#color

A function may return an invalid value for the rule like `null` or `undefined`. Is there a defined behavior for these cases?

**Comment by meetar** [comment]
Functions must return one of the other supported values, so those cases are treated like any other invalid value – the style will fail to compile.

**Comment by matteblair** [comment]
By "fail to compile", you mean that the geometry for that feature won't be built?

**Comment by meetar** [comment]
Yes, that's correct.

**Comment by matteblair** [comment]
Very interesting! Thanks :)

**Comment by meetar** [comment]
:+1:
