### ISSUE TITLE
Link to Javascript API page is broken

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-docs#66]
In the generated docs, the link on this page https://mapzen.com/documentation/tangram/cameras/ (https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/cameras.md) to this page https://mapzen.com/documentation/tangram/cameras/Javascript-API.md (https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Javascript-API.md) is broken.
I don't yet understand enough about this doc generation process to know why, but wanted to make a note so we can fix.

**Comment by bcamper** [comment]
cc @louh

**Comment by louh** [comment]
cc @migurski

**Comment by migurski** [comment]
cc @bcamper oh wait.

I see the problem, not sure how to fix it since we want the link correct in both Github and on the Docs site.

**Comment by bcamper** [comment]
What is the problem? :)  We can and probably should restructure some of this anyway, so would be helpful to know why and maybe we can work around it.

**Comment by rmglennon** [comment]
I put in an issue to look at restructuring the help https://github.com/tangrams/tangram-docs/issues/67

**Comment by migurski** [comment]
I’m actually surprised that `mkdocs` doesn’t find this link and fix it. @louh, any chance you can investigate to see if there’s an option to fix this there, after Search Demo is complete?

**Comment by meetar** [comment]
This problem turns out to be pervasive throughout the generated docs – on the `cameras.md` page, the first link to scene-file.md is also broken. In all broken cases, the `href` in the `a` tag is composed solely of the file name – eg `"scene-file.md"` – when it should be `"../scene-file.md"`.

I can't find a pattern which describes which inline links are broken and which aren't – the links in the .md files seem to all follow typical markdown link patterns. A link to `"yaml.md#object-types"` is formatted properly, but links to `Cameras-Overview.md` and `Javascript-API.md#get` are not, and on other pages (eg `lights.md` and `materials.md`) I see a broken link to `scene-file.md` and a working link to `style.md`. 🤔

**Comment by rmglennon** [comment]
This is pretty strange. 

In the active paragraph, there are a few anchor links like get and set that are not found in the GitHub site either (get and set aren't the current headings in the markdown and I didn't see any manually inserted anchor tags). So, even on GitHub's site, these links only go to the top of the JavaScript-API page, but on the mapzen site, they are totally dead.

Javascript-API.md#get or Javascript-API.md#set the active camera.

So, we do need to update those anchor tags...but that still doesn't solve why the main JavaScript-API link isn't working on the documentation site.

**Comment by louh** [comment]
This is related: CircleCI produces warnings when you build Tangram documentation:

```
WARNING -  The page "Scene-file.md" contained a hyperlink to "textures.md" which is not listed in the "pages" configuration. 
WARNING -  The page "Shaders-Overview.md" contained a hyperlink to "styles-overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "yaml.md" contained a hyperlink to "filters.md" which is not listed in the "pages" configuration. 
WARNING -  The page "yaml.md" contained a hyperlink to "filters.md" which is not listed in the "pages" configuration. 
WARNING -  The page "cameras.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "cameras.md" contained a hyperlink to "Javascript-API.md" which is not listed in the "pages" configuration. 
WARNING -  The page "cameras.md" contained a hyperlink to "Javascript-API.md" which is not listed in the "pages" configuration. 
WARNING -  The page "cameras.md" contained a hyperlink to "Javascript-API.md" which is not listed in the "pages" configuration. 
WARNING -  The page "lights.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "materials.md" contained a hyperlink to "textures.md" which is not listed in the "pages" configuration. 
WARNING -  The page "materials.md" contained a hyperlink to "textures.md" which is not listed in the "pages" configuration. 
WARNING -  The page "styles.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "styles.md" contained a hyperlink to "textures.md" which is not listed in the "pages" configuration. 
WARNING -  The page "styles.md" contained a hyperlink to "textures.md" which is not listed in the "pages" configuration. 
WARNING -  The page "styles.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "layers.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "draw.md" contained a hyperlink to "Javascript-API.md" which is not listed in the "pages" configuration. 
WARNING -  The page "draw.md" contained a hyperlink to "Javascript-API.md" which is not listed in the "pages" configuration. 
WARNING -  The page "shaders.md" contained a hyperlink to "Javascript-API.md" which is not listed in the "pages" configuration. 
WARNING -  The page "shaders.md" contained a hyperlink to "material.md" which is not listed in the "pages" configuration. 
```

This _should_ be the canonical list of all the broken links (perhaps not in-page anchors, though). There seems to be a few culprits (in addition to the anchor tags):
- File names are case-sensitive. A link looking for `scene-file.md` can't find it because the S is actually capitalized: that is, `Scene-file.md`. 
- Some files need to be included in the documentation's configuration. This is what produces a Table of Contents. If it's not in there, then it "doesn't exist". So files like `Javascript-API.md` and `textures.md` need to be included in https://github.com/mapzen/mapzen-docs-generator/blob/master/config/tangram.yml
- `material.md` is just a typo. It should be `materials.md`

Hope that helps?

As a follow up, we should look into whether the WARNINGs can be converted to ERRORs that notify the right people.

**Comment by rmglennon** [comment]
Wow, @louh. Thanks. Had no idea there were warnings listed. 

@meetar - I can fix the config to get the missing topics onto the doc site (duh, not sure how I missed these weren't in the TOC before).

**Comment by meetar** [comment]
And I'll triple-check those links :D

Thanks @louh and @rmglennon!

**Comment by rmglennon** [comment]
The case-sensitivity thing got me, too (I added JavaScript-API.md and the build failed because it's Javascript-API.md).

**Comment by rmglennon** [comment]
Current list of broken links after I added the missing topics (which should propagate to the website shortly).

WARNING -  The page "Shaders-Overview.md" contained a hyperlink to "styles-overview.md" which is not listed in the "pages" configuration. 
WARNING -  The page "cameras.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "layers.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "lights.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "shaders.md" contained a hyperlink to "material.md" which is not listed in the "pages" configuration. 
WARNING -  The page "styles.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "styles.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "textures.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration. 
WARNING -  The page "Javascript-API.md" contained a hyperlink to "scene-file.md" which is not listed in the "pages" configuration.

**Comment by meetar** [comment]
The broken links in the .md files have been edited, but the corresponding links in the docs are still broken. However, the `config/tangram.yml` updates have propagated and the related links are now fixed.

**Comment by meetar** [comment]
Links fixed! teamwork.gif
