### ISSUE TITLE
tron link broken again

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#72]
http://www.citylab.com/design/2015/03/a-mesmerizing-futuristic-map-with-animated-traffic-and-glowing-buildings/388285/

links to 

http://tangrams.github.io/tangram-docs-assets/?procedural/tronish.yaml#16/40.7053/-74.0098

which forwards to 

http://tangrams.github.io/tangram-docs?procedural/tronish.yaml#16/40.7053/-74.0098

which is a 404.

**Comment by bcamper** [comment]
Fixed by https://github.com/tangrams/tangram-docs-assets/commit/6f0cc2b6716383240b9879486421c86c60900f33

(also made the old repo private since it just exists for redirects and the gh-pages branch will continue to serve publicly)

**Comment by bcamper** [comment]
(I verified but had to use an incognito window to avoid caching)
