### ISSUE TITLE
Add Tangram Android SDK documentation

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#81]
The [tangram-es](https://github.com/tangrams/tangram-es) Android SDK will be launching publicly in the next few weeks. The public tangram documentation (https://mapzen.com/documentation/tangram/) should cover both the browser-based and Android-based Tangram SDKs. I can see several major steps to completing this:
- [x] Find and label parts of the docs specific to tangram-js (e.g. "Walkthrough" -> "JS Walkthrough")
- [x] Re-word the "Home" page to include both the web and mobile versions of tangram
- [x] Create a repository with a minimal tangram-es Android demo app
- [x] Add an "Android Walkthrough" page
- [x] Add Android API reference documentation (either javadoc or markdown generated from javadoc)

**Comment by matteblair** [comment]
@meetar @rmglennon I'll be asking for help from both of you for this. Two questions to start:
1. Do these steps make sense?
2. How do the markdown files in this repo relate to the pages on mapzen.com?

**Comment by rmglennon** [comment]
Before we dig in on the mechanics of reorganizing help, I'd like to think more about how we organize this content and how Tangram JS, ES, Android, and mobile SDKs all fit together in documentation and as products.

A few things I was thinking about:
- How do we package our mobile SDK documentation and products? 
- Would someone working on mobile only expect to see content for JS (and vice versa)?
- Do we expect more users to use Tangram JS or Android/ES?
- How much overlap is there in the contents of the JS and Android/ES documentation?
- Is there a help system that covers all the mobile SDKs, including Tangram Android?
- Is mobile development and this SDK more closely tied than the two Tangrams? Note that it is possible to have docs duplicated under both Tangram and mobile SDKs (from one set of md files).

**Comment by mjcunningham** [comment]
I think that the generic Android SDK documentation should be separate from the tangram specific stuff but it should be easy to find if you want to dig in. 

@blair1618 @ecgreb @sarahlensing  (Correct me if I'm wrong here) 
I feel like most people will be doing things like interacting w the helpers for lines and pins and changing style sheets and that all happens in the Android SDK so the documentation should live there. If they wanted to dig into tangram we should point them into the tangram docs.

**Comment by meetar** [comment]
@rmglennon Yes, these are good things to consider! I have an issue over at #67 just for them, so I'll just say here that I agree the Android SDK should probably have its own place, but there could definitely be links between the two places, and @blair1618 1) Yes! I think those steps make sense, and  2) I'll try to describe all of that as part of #67 :)

**Comment by meetar** [comment]
@rmglennon Yes, these are good things to consider, let's talk about that over at #67! I'll just say here that I agree the Android SDK should probably have its own place, but there could definitely be links between the two places, and also @blair1618 1) Yes! I think those steps make sense, and  2) I'll try to describe all of that as part of #67 and we can leave this issue for Android DSK-specific stuff.

**Comment by meetar** [comment]
[shakes a fist at his dodgy internet connection]

**Comment by matteblair** [comment]
@rmglennon I would tend to agree with how Mike described the differences. The Mapzen Android SDK will offer simplified interfaces to the Tangram Android SDK and I imagine that it will serve as many people's introduction to Tangram, but it will be sufficiently different that it should have separate documentation from the Tangram Android SDK, with ways to find out more about Tangram if a person wants to.

**Comment by bcamper** [comment]
Agreed, for now I would like to see:
- Tangram docs section
  - Scene file
  - JS API
  - Android SDK
- Mapzen SDK section
  - salient/common calls for setting up a map, link to Tangram docs for advanced things like making custom scenes

We'll see how this goes and I imagine we'll be changing it up or finding better ways to integrate them as we better understand real-world scenarios.

**Comment by ecgreb** [comment]
+1 @bcamper. Mapzen SDK docs will also need to cover things like setting up your API key and value-added integrations (like the current location tracking layer). We are working on a sample app in the SDK repo that will cover all common use cases such as these.

https://github.com/mapzen/android/tree/master/sample

**Comment by matteblair** [comment]
Everything I had originally wanted for this has been implemented now. Thanks everyone!
