### ISSUE TITLE
Add a demos page

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#83]
This would be a top-level page which would collect and foreground all of our otherwise uncollected demos (eg, https://github.com/tangrams/?utf8=%E2%9C%93&query=demo) – plus any other maps we've made which could be useful for learning the library.

**Comment by bcamper** [comment]
📖

**Comment by nvkelso** [comment]
+1

**Comment by meetar** [comment]
fixed with https://github.com/tangrams/tangram-docs/pull/85
