### ISSUE TITLE
Simple scene example uses nonexistent syntax

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#87]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Scene-file.md#the-basics

Maybe we had syntax like this a long time ago? We need an updated minimum-viable-scene.

**Comment by meetar** [comment]
It's quite likely to be out of date! Can you say describe what caught your eye?

**Comment by bcamper** [comment]
Updated with https://github.com/tangrams/tangram-docs/commit/ea4a9ddb47293249b42d7ef4c38d9fa10b0f7d40
