### ISSUE TITLE
Dead links in shaders reference page

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#9]
The links to "Javascript API", "built-in uniforms", and "varyings" in the uniforms section are 404 

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#uniforms

As is the link to "UV maps" in the material parameters section

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#material-parameters

**Comment by matteblair** [comment]
And also the link to... "link" in the defines section

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#defines

**Comment by meetar** [comment]
fixed, thanks!
