### ISSUE TITLE
document label centroids

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#91]
`generate_label_centroids`

This will go in https://mapzen.com/documentation/tangram/sources/

`label_placement`

Probably need a new section in https://mapzen.com/documentation/tangram/filters/#feature-properties - something like "pre-processed features", noting that this is something Tangram can add, linking to the sources section.

**Comment by burritojustice** [comment]
@meetar @dmvaldman can we also get an example of how this would be implemented in yaml?

**Comment by meetar** [comment]
Certainly!

**Comment by dmvaldman** [comment]
Here's a Tangram play link to an example: http://mapzen.com/tangram/play/?scene=https://gist.githubusercontent.com/anonymous/986bdf7b4d5e8e66f542db85fa223ee8/raw/4c29bd5097e3793ecb08d9820587eb06badca5f5/scene.yaml#14/40.7862/-73.9649

This won't work for Tangram Play on v0.7.2 of Tangram, but I've tested it against the latest Tangram and it works there. When Tangram Play is updated to v0.8, this example should show the centroid label for a geojson polygon around Central Park.

**Comment by meetar** [comment]
Resolved with https://github.com/tangrams/tangram-docs/pull/92 and https://github.com/tangrams/tangram-docs/pull/107
