### ISSUE TITLE
v0.8.0 docs

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#94]
- [x] unified text/points style (https://github.com/tangrams/tangram/pull/306)
- [x] dashed lines (https://github.com/tangrams/tangram/pull/312)
- [x] line textures (tangrams/tangram#312)
- [x] custom fonts (https://github.com/tangrams/tangram/pull/326)
- [x] introspection mode (https://github.com/tangrams/tangram/pull/303)
- [x] centroid labeling (https://github.com/tangrams/tangram/pull/302)

**Comment by bcamper** [comment]
I added a label for things that need docs:

https://github.com/tangrams/tangram/issues?utf8=%E2%9C%93&q=label%3Aneeds-docs+

**Comment by meetar** [comment]
:+1:, thanks!

**Comment by meetar** [comment]
unified text/point style added with 4f12342820454c7d725dee4b81bba3daaba46ddc
dashes added with b3dc103c2622caeef6f9f6dcdf0e07c6de03b81c
line texture added with d343922caee6e76ac1086b408c8ef252b8fa4753
fonts added with 64e266909444347cde4b6f514dcda88f69745dbb
introspection mode added with d8dff6717320bca9cee541f442b8dccacb3fbf0b
centroid labeling added with 870e816b8476c91d419c03d03a63338c38e7be6c
