### ISSUE TITLE
Link to import page

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-docs#96]
It looks like we have a page for scene `import`, but I don't see a link to it anywhere? We should add it to the nav (and possibly link elsewhere too).

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/import.md

**Comment by meetar** [comment]
Resolves with https://github.com/mapzen/mapzen-docs-generator/pull/149 and 565ea5f09299797b415e13d3888c6e34c5d3a537
